"""
R engine bridge via subprocess (Rscript). More stable than rpy2, avoids segfaults.
Passes data via CSV files, returns results as parsed output.
"""

import os
import sys
import json
import tempfile
import subprocess
from pathlib import Path
from typing import List, Dict, Optional


def _find_r_home() -> str:
    """Locate R installation."""
    candidates = []
    if getattr(sys, 'frozen', False):
        meipass = Path(sys._MEIPASS)
        candidates.append(str(meipass / '..' / '..' / 'runtime' / 'R'))
    candidates.extend([
        str(Path(__file__).parent.parent.parent / 'runtime' / 'R'),
        os.environ.get('R_HOME', ''),
        'C:/Program Files/R/R-4.6.0',
    ])
    for c in candidates:
        exe = Path(c) / 'bin' / 'Rscript.exe'
        if exe.exists():
            return str(Path(c) / 'bin' / 'R.exe')
    raise RuntimeError("R not found. Please install R.")


def _rscript_exe() -> str:
    r_home = _find_r_home()
    return str(Path(r_home).parent / 'Rscript.exe')


_RSCRIPT = None


def run_r(code: str, timeout: int = 300) -> str:
    """Execute R code via Rscript, return stdout."""
    global _RSCRIPT
    if _RSCRIPT is None:
        _RSCRIPT = _rscript_exe()

    with tempfile.NamedTemporaryFile(mode='w', suffix='.R', delete=False, encoding='utf-8') as f:
        f.write(code)
        script_path = f.name

    try:
        result = subprocess.run(
            [_RSCRIPT, '--no-save', '--no-restore', script_path],
            capture_output=True, text=True, timeout=timeout,
            env={**os.environ, 'R_HOME': str(Path(_RSCRIPT).parent.parent)},
        )
        if result.returncode != 0:
            raise RuntimeError(f"R error (code {result.returncode}): {result.stderr[:500]}")
        return result.stdout
    finally:
        try:
            os.unlink(script_path)
        except Exception:
            pass


def run_r_with_data(code_template: str, data_files: Dict[str, str], timeout: int = 300) -> str:
    """Execute R code that reads from data files, return stdout + any output files."""
    global _RSCRIPT
    if _RSCRIPT is None:
        _RSCRIPT = _rscript_exe()

    tmpdir = tempfile.mkdtemp(prefix='r_run_')
    script_path = os.path.join(tmpdir, 'script.R')

    # Write data files
    for name, content in data_files.items():
        Path(tmpdir, name).write_text(content, encoding='utf-8')

    # Write R script with paths substituted
    r_code = code_template
    for name in data_files:
        r_code = r_code.replace(f'{{{{{name}}}}}', str(Path(tmpdir, name).as_posix()))

    Path(script_path).write_text(r_code, encoding='utf-8')

    try:
        result = subprocess.run(
            [_RSCRIPT, '--no-save', '--no-restore', script_path],
            capture_output=True, text=True, timeout=timeout,
            cwd=tmpdir,
            env={**os.environ, 'R_HOME': str(Path(_RSCRIPT).parent.parent)},
        )
        if result.returncode != 0:
            raise RuntimeError(f"R error (code {result.returncode}): {result.stderr[:500]}")

        # Check for output files generated by R
        output = {'stdout': result.stdout, 'files': {}}
        for f in Path(tmpdir).glob('output_*'):
            output['files'][f.name] = f.read_text(encoding='utf-8')

        return json.dumps(output)
    finally:
        import shutil
        try:
            shutil.rmtree(tmpdir, ignore_errors=True)
        except Exception:
            pass


def test_r() -> bool:
    """Quick test that R is working."""
    try:
        out = run_r('cat("R OK\\n"); sessionInfo()$R.version$version.string')
        return 'R OK' in out
    except Exception as e:
        print(f"R test failed: {e}")
        return False
